#include "GlobalConfigs.h"
#include "MMTStringUtils.h"
#include "MMTFileUtils.h"
#include "ModFormatExtra.h"
#include "GlobalFunctions.h"
#include "IndexBufferBufFile.h"
#include "FmtData.h"

//This function is mainly designed for merged mod generated by using namespace technique scripts from Qwerty3Yuiop
// https://gamebanana.com/tools/15681
// https://gamebanana.com/tools/16337
//TODO Lv3已经过时了,完成这个之前需要先Toggle的解析支持
void Reverse_Lv4_Merged_NameSpace() {


}